hw-10/hw10/hw10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

hw-10/hw10/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.get_quotes, name="main"),
    path("<int:page>", views.get_quotes, name="quotes_pagination"),
    path("author/<str:fullname>", views.get_author, name="author"),
    path("create-author", views.create_author, name="create_author"),
    path("create-quote", views.create_quote, name="create_quote"),
]

hw-10/hw10/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
]

hw-10/hw10/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    tag = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f"{self.tag}"


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.SET_NULL, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quote}"

hw-10/hw10/users/models.py
from django.db import models

# Create your models here.

hw-10/hw10/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea
from .models import Author, Quote


class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    born_date = CharField(
        min_length=3, max_length=50, required=True, widget=TextInput()
    )
    born_location = CharField(
        min_length=3, max_length=150, required=True, widget=TextInput()
    )
    description = CharField(min_length=10, required=True, widget=Textarea())

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuoteForm(ModelForm):
    quote = CharField(min_length=10, required=True, widget=Textarea())

    class Meta:
        model = Quote
        fields = ["quote"]
        exclude = ["tags", "author"]

hw-10/hw10/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())

    password1 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        max_length=50, required=True, widget=forms.PasswordInput()
    )


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]

hw-10/hw10/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import HttpResponse

from .forms import AuthorForm, QuoteForm
from .models import Quote, Author, Tag


def get_quotes(request, page=1):
    quotes = Quote.objects.all().order_by("-created_at")

    par_page = 10

    paginator = Paginator(quotes, par_page)

    return render(
        request,
        "quotes/quotes.html",
        context={
            "quotes": paginator.page(page),
        },
    )


def get_author(request, fullname):
    try:
        author = Author.objects.get(fullname=fullname)
    except Author.DoesNotExist:
        return HttpResponse(f"<h1>Author with name - {fullname} does not exist</h1>")

    return render(
        request,
        "quotes/author.html",
        context={
            "author": author,
        },
    )


@login_required
def create_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)

        if form.is_valid():
            author = form.save(commit=False)
            author.save()

            return redirect(to="quotes:author", fullname=form.cleaned_data["fullname"])
        else:
            return render(
                request,
                "quotes/create_author.html",
                context={
                    "form": form,
                },
            )

    return render(
        request,
        "quotes/create_author.html",
        context={
            "form": AuthorForm(),
        },
    )


@login_required
def create_quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            a = Author.objects.get(id=request.POST["author"])
            q = Quote.objects.create(
                quote=request.POST["quote"],
                author=a,
            )

            for tag in request.POST.getlist("tags"):
                q.tags.add(tag)

            return redirect(to="quotes:main")
        else:
            return render(
                request,
                "quotes/create_quote.html",
                context={
                    "form": form,
                    "tags": tags,
                    "authors": authors,
                },
            )

    return render(
        request,
        "quotes/create_quote.html",
        context={
            "form": QuoteForm(),
            "tags": tags,
            "authors": authors,
        },
    )

hw-10/hw10/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterForm, LoginForm


def signup(request):
    if request.user.is_authenticated:
        return redirect(to="quotes:main")

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(to="quotes:main")
        else:
            return render(request, "users/signup.html", {"form": form})

    return render(request, "users/signup.html", {"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to="quotes:main")

    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"], password=request.POST["password"]
        )

        if user is None:
            messages.error(request, "Username or password didn't match")
            return redirect(to="users:login")

        login(request, user)
        return redirect(to="quotes:main")

    return render(request, "users/login.html", context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to="quotes:main")

hw-10/hw10/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>

{% endblock %}

hw-10/hw10/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% load static %}

    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>


<div class="container">
    <div class="row header-box">
        <div class="col-md-6">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-6">
            {% if user.is_authenticated %}

            <ul>
                <li><a href="{% url 'quotes:create_quote' %}" role="button">Add quote</a></li>
                <li><a href="{% url 'quotes:create_author' %}" role="button">Add author</a></li>
            </ul>
            <ul>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>

            {% else %}

            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>

            {% endif %}
        </div>
    </div>

    {% block content %} {% endblock %}
</div>
</body>
</html>

hw-10/hw10/quotes/templates/quotes/create_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:create_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author name:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

hw-10/hw10/quotes/templates/quotes/create_quote.html
{% extends "quotes/base.html" %}

{% block content %}


<form method="POST" action="{% url 'quotes:create_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>

    <div style="padding: 10px">
        <label> Select author:
            <select name="author" required>
                {% for author in authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.id}}">{{tag.tag}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

hw-10/hw10/quotes/templates/quotes/quotes.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-8">

        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
        <a href="/author/{{ quote.author }}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world">

                {% for tag in quote.tags.all %}

                <a class="tag" href="/tag/change/page/1/">{{ tag }}</a>

                {% endfor %}
            </div>
        </div>

        {% endfor %}

        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:quotes_pagination' quotes.previous_page_number %} {% else %} # {% endif %}"><span
                            aria-hidden="true">←</span> Previous</a>
                </li>
                <li class="next">
                    <a
                        class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:quotes_pagination' quotes.next_page_number %} {% else %} # {% endif %}">Next
                        <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
    </div>

    <!--    <div class="col-md-4 tags-box">-->

    <!--        <h2>Top Ten tags</h2>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 28px" href="/tag/love/">love</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 26px" href="/tag/inspirational/">inspirational</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 26px" href="/tag/life/">life</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 24px" href="/tag/humor/">humor</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 22px" href="/tag/books/">books</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 14px" href="/tag/reading/">reading</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 10px" href="/tag/friendship/">friendship</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 8px" href="/tag/friends/">friends</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 8px" href="/tag/truth/">truth</a>-->
    <!--            </span>-->

    <!--        <span class="tag-item">-->
    <!--            <a class="tag" style="font-size: 6px" href="/tag/simile/">simile</a>-->
    <!--            </span>-->


    <!--    </div>-->
</div>

{% endblock %}

hw-10/hw10/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

hw-10/hw10/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}